#:schema node_modules/wrangler/config-schema.json
name = "cloudflare-astro-blog"
compatibility_date = "2025-01-10"
compatibility_flags = ["nodejs_compat"]

# Pages project settings (Astro builds to dist/ by default)
pages_build_output_dir = "./dist"

# KV namespace for Astro sessions
[[kv_namespaces]]
binding = "SESSION"
id = "d369ffef589146d19f402ebe91586745"

# Note: account_id is not needed for Pages deployments (wrangler uses OAuth)
